default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: admin

development:
  <<: *default
  database: meal_orders_development

test:
  <<: *default
  database: meal_orders_test

production:
  database: meal_orders_production
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres #<%= ENV['DATABASE_USERNAME'] %>
  password: admin #<%= ENV['DATABASE_PASSWORD'] %>
