default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: You username
  password: Your password

development:
  <<: *default
  database: lists_manager_development

test:
  <<: *default
  database: lists_manager_test

production:
  <<: *default
  database: lists_manager_production
  username: postgres #<%= ENV['DATABASE_USERNAME'] %>
  password: admin #<%= ENV['DATABASE_PASSWORD'] %>
